---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
library(phylodyn)

date_min <- 1990
date_max <- 2021

trajectory_bottleneck <- function(t){
    result = rep(0, length(t))
    result[t <= 2005] <- 10
    result[t > 2005 & t < 2021] <- 1
    result[t >= 2021] <- 10
    return(result)
}

n.sim <- 500 # number of simulations

#20 taxa
stimes20 <- sort(runif(20, date_min, date_max))

genealogies_20taxa <- lapply(1:n.sim, function(i){
  phylodyn::coalsim(samp_times = stimes20,
                    n_sampled = rep(1,20),
                    traj = trajectory_bottleneck,
                    lower_bound = 1)
})


#200 taxa
stimes200 <- sort(runif(200, date_min, date_max))

genealogies_200taxa <- lapply(1:n.sim, function(i){
  phylodyn::coalsim(samp_times = stimes200,
                    n_sampled = rep(1,200),
                    traj = trajectory_bottleneck,
                    lower_bound = 1)
})
```

```{r}
system.time(
  reconstructions_20taxa_gamma <- lapply(genealogies_20taxa, function(x)
    BNPR(data = x, lengthout =100))
)

system.time(
  reconstructions_20taxa_gumbel <- lapply(genealogies_20taxa, function(x)
    BNPR(data = x, lengthout = 100, 
         pc_prior = TRUE))
)
```

```{r}
#Phylodynamic reconstruction of effective population size  200 taxa

system.time(
  reconstructions_200taxa_gamma <- lapply(genealogies_200taxa, function(x)
    BNPR(data = x, lengthout = 100))
)

system.time(
  reconstructions_200taxa_gumbel <- lapply(genealogies_200taxa, function(x)
    BNPR(data = x, lengthout = 100, 
         pc_prior = TRUE))
)
```

```{r}
summaries_gamma_20taxa <- do.call(rbind, lapply(1:n.sim, function(i){
  data.frame(reconstructions_20taxa_gamma[[i]]$summary, replicate = i,
             prior = "Gamma", ntaxa = "20")}))

summaries_gumbel_20taxa <- do.call(rbind, lapply(1:n.sim, function(i){
  data.frame(reconstructions_20taxa_gumbel[[i]]$summary, replicate = i, 
             prior = "Gumbel", ntaxa = "20")
}))

summaries_gamma_200taxa <- do.call(rbind, lapply(1:n.sim, function(i){
  data.frame(reconstructions_200taxa_gamma[[i]]$summary,
             replicate = i, prior = "Gamma", ntaxa = "200")
}))

summaries_gumbel_200taxa <- do.call(rbind, lapply(1:n.sim, function(i){
  data.frame(reconstructions_200taxa_gumbel[[i]]$summary,
             replicate = i,
             prior = "Gumbel", ntaxa = "200", )
}))

all_estimates <- rbind(summaries_gamma_20taxa, summaries_gumbel_20taxa,
                       summaries_gamma_200taxa, summaries_gumbel_200taxa)

all_estimates$ntaxa <- as.factor(all_estimates$ntaxa)
head(all_estimates)

```
Saving data frames in a txt file:
```{r}
#write.table(x,"filename.txt",sep="\t",row.names=FALSE)
```


Plotting the effective population size:
```{r}
for_plot <- all_estimates
for_plot$replicate <- as.factor(for_plot$replicate)
options(repr.plot.width = 10, repr.plot.height = 7)
peffpop <- ggplot(data = for_plot) +
    scale_x_continuous("Times (years)", expand = c(0,0)) +
    scale_y_continuous("Effective population size (mean)", expand = c(0,0)) +
    geom_line(aes(x = time, y = mean, col = prior, group = replicate), alpha = .5) + 
    facet_grid(ntaxa~prior, scales = "free_y") +
    guides(col = "none") +
    theme_bw() +
    stat_function(fun = trajectory_bottleneck, colour = 'black') +
    NULL

peffpop
ggsave("Imagens/effective_pop_mean_bottleneck.pdf",
       plot = peffpop)
```
Plotting a random individual case:
```{r}
options(repr.plot.width = 10, repr.plot.height = 7)

```



Calculating the percent error:

```{r}

```

