---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
library(phylodyn)

set.seed(29)

date_min <- 1990
date_max <- 2021

trajectory_exponential <- function(t, scale = 10, rate = 0.1){
    return(scale * exp(- (t - 1990) * rate))
}

#Plotting the trajectory
plot(trajectory_exponential(seq(1990, 2021)), type = 'l')

n.sim <- 500 # number of simulations

#20 taxa
stimes20 <- sort(runif(20, date_min, date_max))

genealogies_20taxa <- lapply(1:n.sim, function(i){
  phylodyn::coalsim(samp_times = stimes20,
                    n_sampled = rep(1,20),
                    traj = trajectory_exponential,
                    lower_bound = 0)
})

#Ploting one of the trees
tree <- sample_tree(genealogies_20taxa[[1]])
plot(tree)

```

```{r}
#200 taxa
stimes200 <- sort(runif(200, date_min, date_max))

genealogies_200taxa <- lapply(1:n.sim, function(i){
  phylodyn::coalsim(samp_times = stimes200,
                    n_sampled = rep(1,200),
                    traj = trajectory_exponential,
                    lower_bound = 0)
})

#Ploting one of the trees
tree200 <- sample_tree(genealogies_200taxa[[1]])
plot(tree200)
```


```{r, verbose = TRUE}
#Gamma Flat
Csystem.time(
  reconstructions_20taxa_gamma <- lapply(genealogies_20taxa, function(x)
    BNPR(data = x, lengthout =100, prec_alpha = 0.001, prec_beta = 0.001))
)


#PC Prior
system.time(
  reconstructions_20taxa_gumbel <- lapply(genealogies_20taxa, function(x)
    BNPR(data = x, lengthout = 100, 
         pc_prior = TRUE))
)

#Matching Gamma
par_ab <- c(2.544882, 1.203437)
system.time(
  reconstructions_20taxa_gamma2 <- lapply(genealogies_20taxa, function(x)
    BNPR(data = x, lengthout =100, prec_alpha = par_ab[1], prec_beta = 1/par_ab[2]))
)
```

```{r}
#Phylodynamic reconstruction of effective population size  200 taxa

#Gamma 1
system.time(
  reconstructions_200taxa_gamma <- lapply(genealogies_200taxa, function(x)
    BNPR(data = x, lengthout = 100, prec_alpha = 0.001, prec_beta = 0.001))
)

#PC prior
system.time(
  reconstructions_200taxa_gumbel <- lapply(genealogies_200taxa, function(x)
    BNPR(data = x, lengthout = 100, 
         pc_prior = TRUE))
)

#Matching Gamma
par_ab <- c(2.544882, 1.203437)
system.time(
  reconstructions_20taxa_gamma2 <- lapply(genealogies_20taxa, function(x)
    BNPR(data = x, lengthout =100, prec_alpha = par_ab[1], prec_beta = 1/par_ab[2]))
)
```

```{r}
#Summaries gamma 20 taxa
summaries_gamma_20taxa <- do.call(rbind, lapply(1:n.sim, function(i){
  data.frame(reconstructions_20taxa_gamma[[i]]$summary, replicate = i,
             prior = "Gamma Flat", ntaxa = "20")
}))

summaries_gumbel_20taxa <- do.call(rbind, lapply(1:n.sim, function(i){
  data.frame(reconstructions_20taxa_gumbel[[i]]$summary, replicate = i, 
             prior = "Gumbel", ntaxa = "20")
}))

summaries_gamma2_20taxa <- do.call(rbind, lapply(1:n.sim, function(i){
  data.frame(reconstructions_20taxa_gamma2[[i]]$summary, replicate = i, 
             prior = "Matching Gamma", ntaxa = "20")
}))

summaries_gamma_200taxa <- do.call(rbind, lapply(1:n.sim, function(i){
  data.frame(reconstructions_200taxa_gamma[[i]]$summary,
             replicate = i, prior = "Gamma Flat", ntaxa = "200")
}))

summaries_gamma2_200taxa <- do.call(rbind, lapply(1:n.sim, function(i){
  data.frame(reconstructions_200taxa_gamma2[[i]]$summary,
             replicate = i, prior = "Matching Gamma", ntaxa = "200")
}))

summaries_gumbel_200taxa <- do.call(rbind, lapply(1:n.sim, function(i){
  data.frame(reconstructions_200taxa_gumbel[[i]]$summary,
             replicate = i,
             prior = "Gumbel", ntaxa = "200")
}))

all_estimates <- rbind(summaries_gamma_20taxa, summaries_gamma2_20taxa,
                       summaries_gumbel_20taxa,
                       summaries_gamma2_200taxa,
                       summaries_gamma_200taxa, summaries_gumbel_200taxa)

all_estimates$ntaxa <- as.factor(all_estimates$ntaxa)
head(all_estimates)

```


Plotting five random individuals simulations for 20 taxa:
```{r}
random_numbers <- sample(1:500, 5)

for (k in 1:5) {
  plot_BNPR(reconstructions_20taxa_gamma[[random_numbers[k]]], traj = trajectory_exponential,
          main= paste("BNPR: Simulation", random_numbers[k]) , 
          yscale = 1,
          col = 'coral', 
          heatmap_labels_side = "left")
}
```


```{r}
for (k in 1:5) {
  plot_BNPR(reconstructions_20taxa_gumbel[[random_numbers[k]]], traj = trajectory_exponential,
          main= paste("BNPR: Simulation", random_numbers[k]) , 
          yscale = 1,
          col = 'turquoise', 
          heatmap_labels_side = "left")
}
```


Matching Gamma
Plotting five random individuals simulations for 20 taxa:
```{r}
for (k in 1:5) {
  plot_BNPR(reconstructions_20taxa_gamma2[[random_numbers[k]]], traj = trajectory_exponential,
          main= paste("BNPR: Simulation", random_numbers[k]) , 
          yscale = 1,
          col = 'green', 
          heatmap_labels_side = "left")
}
```


Plotting random individuals simulations for 200 taxa: 
```{r}
for (k in 1:5) {
  plot_BNPR(reconstructions_200taxa_gamma[[random_numbers[k]]], traj = trajectory_exponential,
          main= paste("BNPR: Simulation", random_numbers[k]) , 
          yscale = 1,
          col = 'coral', 
          heatmap_labels_side = "left")
}

```

```{r}
for (k in 1:5) {
  plot_BNPR(reconstructions_200taxa_gumbel[[random_numbers[k]]], traj = trajectory_exponential,
          main= paste("BNPR: Simulation", random_numbers[k]) , 
          yscale = 1,
          col = 'turquoise', 
          heatmap_labels_side = "left")
}
```

```{r}
for (k in 1:5) {
  plot_BNPR(reconstructions_200taxa_gamma2[[random_numbers[k]]], traj = trajectory_exponential,
          main= paste("BNPR: Simulation", random_numbers[k]) , 
          yscale = 1,
          col = 'green', 
          heatmap_labels_side = "left")
}

```


Calculating performance metrics:
```{r}
#20 taxa
percent_error <- function(x){
  return(100 * (1/date_max) * sum((x$effpop - 10)/10))
}
  
errors_gamma_20taxa <- unlist(lapply(reconstructions_20taxa_gamma, percent_error(x)))

errors_gumbel_20taxa <- unlist(lapply(reconstructions_20taxa_gumbel, percent_error(x)))

errors_gamma2_20taxa <- unlist(lapply(reconstructions_20taxa_gamma2, percent_error(x)))

#Size of the posterior BC:
#20 taxa
width <- function(x){
  return((1/date_max) * sum((x$effpop975 - x$effpop025)/10))
}

widths_gamma_20taxa <- unlist(lapply(reconstructions_20taxa_gamma, width(x)))

widths_gumbel_20taxa <- unlist(lapply(reconstructions_20taxa_gumbel, width(x)))

widths_gamma2_20taxa <- unlist(lapply(reconstructions_20taxa_gamma2, width(x)))

#200 taxa
errors_gamma_200taxa <- unlist(lapply(reconstructions_20taxa_gamma, percent_error(x)))

errors_gumbel_200taxa <- unlist(lapply(reconstructions_20taxa_gumbel, percent_error(x)))

errors_gamma2_200taxa <- unlist(lapply(reconstructions_20taxa_gamma2, percent_error(x)))

#Width 200taxa
widths_gamma_200taxa <- unlist(lapply(reconstructions_200taxa_gamma, width(x)))

widths_gumbel_200taxa <- unlist(lapply(reconstructions_200taxa_gumbel, width(x)))

widths_gamma2_200taxa <- unlist(lapply(reconstructions_200taxa_gamma2, width(x)))

errors_dt <- data.frame(
  bias = c(errors_gamma_20taxa, errors_gamma_200taxa, errors_gumbel_200taxa, 
           errors_gumbel_200taxa,
           errors_gamma2_200taxa, errors_gamma2_200taxa),
  
  widths = c(widths_gamma_20taxa, widths_gamma_200taxa, 
             widths_gumbel_20taxa, widths_gumbel_200taxa,
             widths_gamma2_20taxa, widths_gamma2_200taxa),
  
  ntaxa = rep(c("20", "200"), 3*nrep),
  
  prior = rep(c("Gamma Flat", "Gamma 2", "Gumbel"), each = 2*nrep)
)
```


```{r}
#Percent bias:
pb <- ggplot(data = errors_dt, aes(x = prior, y = bias, fill= prior)) + 
  geom_boxplot(alpha = .2) +
  scale_y_continuous("Percent bias") +
  geom_hline(yintercept = 0, linetype = "longdash") +
  facet_grid(.~ ntaxa) +
  theme_bw()
pb
```

```{r}
#Percent error:
pe <- ggplot(data = errors_dt, aes(x = prior, y = abs(bias), fill = prior)) +
  geom_boxplot(alpha = .2) +
  scale_y_continuous("Percent error") +
  geom_hline(yintercept = 0, linetype = "longdash") +
  facet_grid(.~ ntaxa) +
  theme_bw()

pe
```

```{r}
pw <- ggplot(data = errors_dt, aes(x = prior, y = widths, fill = prior)) +
  geom_boxplot(alpha = .2) +
  scale_y_log10("Relative width of 95% BCI") +
  facet_grid(.~ ntaxa) +
  theme_bw()

pw
```

Plotting the effective population size mean:
```{r}
for_plot <- all_estimates
for_plot$replicate <- as.factor(for_plot$replicate)
options(repr.plot.width = 10, repr.plot.height = 7)
peffpop <- ggplot(data = for_plot) +
    scale_x_continuous("Times (years)", expand = c(0,0)) +
    scale_y_continuous("Effective population size (mean)", expand = c(0,0)) +
    geom_line(aes(x = time, y = mean, col = prior, group = replicate), alpha = .5) + 
    facet_grid(ntaxa~prior, scales = "free_y") +
    guides(col = "none") +
    theme_bw() +
    stat_function(fun = trajectory_bottleneck, colour = 'black') +
    NULL

peffpop
```

```{r}
ggsave("Imagens/effective_pop_mean_bottleneck.pdf",
       plot = peffpop)
```
