---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
library(phylodyn)
library(rlist) #used to save the datasets

set.seed(29)

date_min <- 0
date_max <- 31

const10 <- function(x){
  return(rep(10, length(x)))
}

nrep <- 500

#Uniform distribution - 20 observations
stimes20 <- sort(runif(20, date_min, date_max))

#Genealogies
#(taxa — pl.) Any named group of organisms (e.g., the reptiles, Felidae, beetles, Homo sapiens).

genealogies_20taxa <- lapply(1:nrep, function(i){
  phylodyn::coalsim(samp_times = stimes20,
                    n_sampled = rep(1,20),
                    traj = const10,
                    lower_bound = 1)
})


#200 taxa
stimes200 <- sort(runif(200, date_min, date_max))

genealogies_200taxa <- lapply(1:nrep, function(i){
  phylodyn::coalsim(samp_times = stimes200,
                    n_sampled = rep(1,200),
                    traj = const10,
                    lower_bound = 1)
})
```

```{r}
#Saving genealogies:
  
list.save(genealogies_20taxa, "/home/cristiana/Downloads/7º Período/TCC parte I/Data/Constant/constant_genealogies_20taxa.rdata")

list.save(genealogies_200taxa, "/home/cristiana/Downloads/7º Período/TCC parte I/Data/Constant/constant_genealogies_200taxa.rdata")

```
Loading genealogies
```{r}
genealogies_20taxa <- list.load("/home/cristiana/Downloads/7º Período/TCC parte I/Data/Constant/constant_genealogies_20taxa.rdata")

genealogies_200taxa <- list.load("/home/cristiana/Downloads/7º Período/TCC parte I/Data/Constant/constant_genealogies_200taxa.rdata")
```


```{r}
#Phylodynamic reconstruction of effective population size - 20 taxa
system.time(
  reconstructions_20taxa_gamma <- lapply(genealogies_20taxa, function(x)
    BNPR(data = x, lengthout =100, prec_alpha = 0.001, prec_beta = 0.001))
)

#Gamma 2
par_ab <- c(2.544882, 1.203437)
system.time(
  reconstructions_20taxa_gamma2 <- lapply(genealogies_20taxa, function(x)
    BNPR(data = x, lengthout =100, prec_alpha = par_ab[1], prec_beta = 1/par_ab[2]))
)

#PC Prior
system.time(
  reconstructions_20taxa_gumbel <- lapply(genealogies_20taxa, function(x)
    BNPR(data = x, lengthout = 100, 
         pc_prior = TRUE))
)
```
Save reconstruction
```{r}
list.save(reconstructions_20taxa_gamma, "/home/cristiana/Downloads/7º Período/TCC parte I/Data/Constant/constant_reconstructions_20taxa_gamma.rdata")

list.save(reconstructions_20taxa_gamma2, "/home/cristiana/Downloads/7º Período/TCC parte I/Data/Constant/constant_reconstructions_20taxa_gamma2.rdata")

list.save(reconstructions_20taxa_gumbel, "/home/cristiana/Downloads/7º Período/TCC parte I/Data/Constant/constant_reconstructions_20taxa_gumbel.rdata")

list.save(reconstructions_200taxa_gumbel, "/home/cristiana/Downloads/7º Período/TCC parte I/Data/Constant/constant_reconstructions_200taxa_gumbel.rdata")

list.save(reconstructions_200taxa_gamma2, "/home/cristiana/Downloads/7º Período/TCC parte I/Data/Constant/constant_reconstructions_200taxa_gamma2.rdata")

list.save(reconstructions_200taxa_gamma, "/home/cristiana/Downloads/7º Período/TCC parte I/Data/Constant/constant_reconstructions_200taxa_gamma.rdata")

```


```{r}
#Phylodynamic reconstruction of effective population size - 200 taxa
system.time(
  reconstructions_200taxa_gamma <- lapply(genealogies_200taxa, function(x)
    BNPR(data = x, lengthout = 100))
)

#Gamma 2
par_ab <- c(2.544882, 1.203437)
system.time(
  reconstructions_200taxa_gamma2 <- lapply(genealogies_200taxa, function(x)
    BNPR(data = x, lengthout =100, prec_alpha = par_ab[1], prec_beta = 1/par_ab[2]))
)

#PC prior
system.time(
  reconstructions_200taxa_gumbel <- lapply(genealogies_200taxa, function(x)
    BNPR(data = x, lengthout = 100, 
         pc_prior = TRUE))
)
```

Plotting five random individuals simulations for 20 taxa:
```{r}
random_numbers <- sample(1:500, 5)

for (k in 1:5) {
  plot_BNPR(reconstructions_20taxa_gamma[[random_numbers[k]]], traj = const10,
          main= paste("BNPR: Simulation", random_numbers[k]) , 
          yscale = 1,
          col = 'coral', 
          heatmap_labels_side = "left")
}
```

Plotting random individuals simulations for 200 taxa: 
```{r}
for (k in 1:5) {
  plot_BNPR(reconstructions_200taxa_gamma[[random_numbers[k]]], traj = const10,
          main= paste("BNPR: Simulation", random_numbers[k]) , 
          yscale = 1,
          col = 'coral', 
          heatmap_labels_side = "left")
}

```

Gamma 2
Plotting five random individuals simulations for 20 taxa:
```{r}
for (k in 1:5) {
  plot_BNPR(reconstructions_20taxa_gamma2[[random_numbers[k]]], traj = const10,
          main= paste("BNPR: Simulation", random_numbers[k]) , 
          yscale = 1,
          col = 'limegreen', 
          heatmap_labels_side = "left")
}
```

Plotting random individuals simulations for 200 taxa: 
```{r}
for (k in 1:5) {
  plot_BNPR(reconstructions_200taxa_gamma2[[random_numbers[k]]], traj = const10,
          main= paste("BNPR: Simulation", random_numbers[k]) , 
          yscale = 1,
          col = 'coral', 
          heatmap_labels_side = "left")
}

```

PC prior
```{r}
for (k in 1:5) {
  plot_BNPR(reconstructions_20taxa_gumbel[[random_numbers[k]]], traj = const10,
          main= paste("BNPR: Simulation", random_numbers[k]) , 
          yscale = 1,
          col = 'turquoise', 
          heatmap_labels_side = "left")
}
```

```{r}
for (k in 1:5) {
  plot_BNPR(reconstructions_200taxa_gumbel[[random_numbers[k]]], traj = const10,
          main= paste("BNPR: Simulation", random_numbers[k]) , 
          yscale = 1,
          col = 'turquoise', 
          heatmap_labels_side = "left")
}
```

Calculating performance metrics:

```{r}
#20 taxa
errors_gamma_20taxa <- unlist(lapply(reconstructions_20taxa_gamma, function(x) 100 * (1/stimes20[length(stimes20)]) * sum((x$effpop[x$x <= 31] - 10)/10)))

errors_gamma2_20taxa <- unlist(lapply(reconstructions_20taxa_gamma2, function(x) 100 * (1/stimes20[length(stimes20)]) * sum((x$effpop[x$x <= 31] - 10)/10)))

errors_gumbel_20taxa <- unlist(lapply(reconstructions_20taxa_gumbel, function(x) 100 * (1/stimes20[length(stimes20)]) * sum((x$effpop[x$x <= 31] - 10)/10)))

#Widths
widths_gamma_20taxa <- unlist(lapply(reconstructions_20taxa_gamma, function(x) (1/stimes20[length(stimes20)]) * sum((x$effpop975[x$x <= 31] - x$effpop025[x$x <= 31])/10)))

widths_gamma2_20taxa <- unlist(lapply(reconstructions_20taxa_gamma2, function(x) (1/stimes20[length(stimes20)]) * sum((x$effpop975[x$x <= 31] - x$effpop025[x$x <= 31])/10)))

widths_gumbel_20taxa <- unlist(lapply(reconstructions_20taxa_gumbel, function(x) (1/stimes20[length(stimes20)]) * sum((x$effpop975[x$x <= 31] - x$effpop025[x$x <= 31])/10)))

#200 taxa
errors_gamma_200taxa <- unlist(lapply(reconstructions_200taxa_gamma, function(x) 100 * (1/stimes200[length(stimes200)]) * sum((x$effpop[x$x <= 31] - 10)/10)))

errors_gamma2_200taxa <- unlist(lapply(reconstructions_200taxa_gamma2, function(x) 100 * (1/stimes200[length(stimes200)]) * sum((x$effpop[x$x <= 31] - 10)/10)))

errors_gumbel_200taxa <- unlist(lapply(reconstructions_200taxa_gumbel, function(x) 100 * (1/stimes200[length(stimes200)]) * sum((x$effpop[x$x <= 31] - 10)/10)))

#Width 200taxa
widths_gamma_200taxa <- unlist(lapply(reconstructions_200taxa_gamma, function(x) (1/stimes200[length(stimes200)]) * sum((x$effpop975[x$x <= 31] - x$effpop025[x$x <= 31])/10)))

widths_gamma2_200taxa <- unlist(lapply(reconstructions_200taxa_gamma2, function(x) (1/stimes200[length(stimes200)]) * sum((x$effpop975[x$x <= 31] - x$effpop025[x$x <= 31])/10)))

widths_gumbel_200taxa <- unlist(lapply(reconstructions_200taxa_gumbel, function(x) (1/stimes200[length(stimes200)]) * sum((x$effpop975[x$x <= 31] - x$effpop025[x$x <= 31])/10)))

errors_dt <- data.frame(
  bias = c(errors_gamma_20taxa, errors_gamma_200taxa, errors_gamma2_20taxa, errors_gamma2_200taxa,
           errors_gumbel_200taxa, errors_gumbel_200taxa),
  widths = c(widths_gamma_20taxa, widths_gamma2_20taxa, widths_gamma_200taxa, widths_gamma2_200taxa, 
             widths_gumbel_20taxa, widths_gumbel_200taxa),
  ntaxa = rep(c("20", "200"), 3*nrep),
  prior = rep(c("Gamma Flat", "Matching Gamma", "PC prior"), each = 2*nrep)
)
```

```{r}
pb <- ggplot(data = errors_dt, aes(x = prior, y = bias, fill= prior)) + 
  geom_boxplot(alpha = .2) +
  xlab("Prior") +
  scale_y_continuous("Percent bias") +
  geom_hline(yintercept = 0, linetype = "longdash") +
  facet_grid(.~ ntaxa) +
  theme_bw()
pb
```
```{r}
ggsave("Imagens/percent_bias_constant_trajectory.pdf",
       plot = pb)
```

```{r}
pe <- ggplot(data = errors_dt, aes(x = prior, y = abs(bias), fill = prior)) +
  geom_boxplot(alpha = .2) +
  scale_y_continuous("Percent error") +
  geom_hline(yintercept = 0, linetype = "longdash") +
  xlab("Prior") +
  facet_grid(.~ ntaxa) +
  theme_bw()

pe
```

```{r}
ggsave("Imagens/Simulated data/percent_error_constant_trajectory.pdf",
       plot = pe)
```

```{r}
pw <- ggplot(data = errors_dt, aes(x = prior, y = widths, fill = prior)) +
  geom_boxplot(alpha = .2) +
  scale_y_log10("Relative width of 95% BCI") +
  facet_grid(.~ ntaxa) +
  xlab("Prior") +
  theme_bw()

pw
```
```{r}
ggsave("Imagens/Simulated data/constant/width_constant_trajectory.pdf",
       plot = pw)
```


```{r}
summaries_gamma_20taxa <- do.call(rbind, lapply(1:nrep, function(i){
  data.frame(reconstructions_20taxa_gamma[[i]]$summary, replicate = i,
             prior = "Gamma Flat", ntaxa = "20")
}))

summaries_gamma2_20taxa <- do.call(rbind, lapply(1:nrep, function(i){
  data.frame(reconstructions_20taxa_gamma2[[i]]$summary, replicate = i,
             prior = "Matching Gamma", ntaxa = "20")
}))

summaries_gumbel_20taxa <- do.call(rbind, lapply(1:nrep, function(i){
  data.frame(reconstructions_20taxa_gumbel[[i]]$summary, replicate = i, 
             prior = "PC prior", ntaxa = "20")
}))

summaries_gamma_200taxa <- do.call(rbind, lapply(1:nrep, function(i){
  data.frame(reconstructions_200taxa_gamma[[i]]$summary,
             replicate = i, prior = "Gamma Flat", ntaxa = "200")
}))

summaries_gamma2_200taxa <- do.call(rbind, lapply(1:nrep, function(i){
  data.frame(reconstructions_200taxa_gamma2[[i]]$summary,
             replicate = i, prior = "Matching Gamma", ntaxa = "200")
}))


summaries_gumbel_200taxa <- do.call(rbind, lapply(1:nrep, function(i){
  data.frame(reconstructions_200taxa_gumbel[[i]]$summary,
             replicate = i,
             prior = "PC prior", ntaxa = "200")
}))

all_estimates <- rbind(summaries_gamma_20taxa,summaries_gamma2_20taxa, summaries_gumbel_20taxa,
                       summaries_gamma_200taxa, summaries_gamma2_200taxa, summaries_gumbel_200taxa)

all_estimates$ntaxa <- as.factor(all_estimates$ntaxa)
head(all_estimates)
```


```{r}
for_plot <- all_estimates
for_plot$replicate <- as.factor(for_plot$replicate)
options(repr.plot.width = 10, repr.plot.height = 7)
peffpop <- ggplot(data = for_plot, aes(x = time, y = mean, col = prior, group = replicate)) +
    scale_x_continuous("Times (years)", expand = c(0,0)) +
    scale_y_continuous("Effective population size (mean)", expand = c(0,0)) +
    geom_line(alpha = .5) + 
    facet_grid(ntaxa~prior, scales = "free_y") +
    guides(col = "none") +
    theme_bw() +
    geom_hline(yintercept = 10, linetype = "dashed", size = .8) +
    NULL

peffpop
```
```{r}
ggsave("Imagens/Simulated data/constant/effective_pop_constant_trajectory.pdf",
       plot = peffpop)
```


```{r}
pd <- ggplot(data = for_plot, aes(x = replicate, y = sd, col = prior)) +
  geom_boxplot(alpha = .3) +
  scale_y_continuous("Standard deviations of effective population size", expand = c(0,0)) +
  facet_grid(prior~.) +
  guides(col = "none") +
  geom_hline(yintercept = 25, linetype = "dashed", size = .8) +
  geom_hline(yintercept = 50, linetype = "dashed", size = .8) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  NULL

pd
```

```{r}
p <- ggplot(data = for_plot, aes(x = prior, y = sd, col = prior, fill = prior)) +
 geom_boxplot(alpha = .3) +
  scale_y_log10("All standard deviations") +
  xlab("Prior") +
  guides(col = "none") +
  guides(fil = "none") +
  theme_bw() +
  NULL

p
```

Saving data that generate the graphs
```{r}
list.save(errors_dt, "/home/cristiana/Downloads/7º Período/TCC parte I/Data/Constant/errors_dt.rdata")
list.save(all_estimates, "/home/cristiana/Downloads/7º Período/TCC parte I/Data/Constant/all_estimates.rdata")
```

